//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanTapHoa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNhapKho
    {
        public int MaCTNK { get; set; }
        public int MaNhapKho { get; set; }
        public int MaSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual NhapKho NhapKho { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
