//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanTapHoa.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhapKho
    {
        public int MaNhapKho { get; set; }
        public int MaCTNK { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    
        public virtual ChiTietNhapKho ChiTietNhapKho { get; set; }
    }
}
